server:
  port: 8082
database:
  driver: mysql
  host: "localhost"
  port: 3306
  username: "cerulean"
  password: "cerulean"
  name: "blog"
tumblr:
  hostname: "chromabits.tumblr.com"
  key: "YOUR KEY GOES HERE"
  postsPerPage: 5
cache:
  address: "localhost:6379"
  password: ""
  database: 0
